Repository insightsengineering/tern, pull requests merged in 2022-07, with the labels that each got.

#622 608 checkmate no stopifnot@main
  R/abnormal_by_baseline.R
  R/coxph.R
  R/decorate_grob.R
  R/g_forest.R
  R/h_response_subgroups.R
  R/h_survival_duration_subgroups.R
  R/prop_diff.R
  R/utils_checkmate.R
  R/utils_factor.R
  R/utils_grid.R
  man/assertions.Rd
  tests/testthat/setup-skip_if_too_deep.R
Labels: enhancement, sme

#612 devops: deprecated h_set_nest_theme
  NEWS.md
  R/individual_patient_plot.R
Labels: sme, core

#629 update installation instructions
  DESCRIPTION
  README.md
Labels: core

#630 621 Remove deprecated `tern` mmrm functions
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/deprec-fit_mmrm.R
  R/deprec-g_mmrm.R
  R/deprec-tabulate_mmrm.R
  _pkgdown.yml
  man/fit_mmrm.Rd
  man/g_mmrm.Rd
  man/g_mmrm_diagnostic.Rd
  man/g_mmrm_lsmeans.Rd
  man/tabulate_mmrm.Rd
Labels: sme, devops

#633 Fixing assertion from `h_adlb_worsen`
  NEWS.md
  R/abnormal_by_worst_grade_worsen.R
Labels: bug, sme

#637 Exported draw_grob function
  NAMESPACE
  NEWS.md
  R/decorate_grob.R
  R/g_forest.R
  R/utils_grid.R
  man/decorate_grob_set.Rd
  man/draw_grob.Rd
  man/g_forest.Rd
Labels: sme

#640 595 Implement `nestcolor` in `tern`
  DESCRIPTION
  NEWS.md
  R/g_forest.R
  R/g_lineplot.R
  R/g_step.R
  R/g_waterfall.R
  R/individual_patient_plot.R
  R/kaplan_meier_plot.R
  R/zzz.R
  man/g_forest.Rd
  man/g_km.Rd
  man/g_lineplot.Rd
  man/g_step.Rd
  man/g_waterfall.Rd
  man/h_ggkm.Rd
  man/individual_patient_plot.Rd
  vignettes/tern.Rmd
Labels: enhancement, sme

#639 generating log-rank p value by survdiff
  NEWS.md
  R/survival_coxph_pairwise.R
  man/h_survival_duration_subgroups.Rd
  man/survival_coxph_pairwise.Rd
  man/survival_duration_subgroups.Rd
  tests/testthat/test-survival_coxph_pairwise.R
Labels: sme

#648 Moving design into another repo (internal)
  design/design_aet01_aesi.Rmd
  design/design_aet04.Rmd
  design/design_aet04_pi.Rmd
  design/design_aet05.Rmd
  design/design_aet06_smq.Rmd
  design/design_aet10.Rmd
  design/design_aovt01.Rmd
  design/design_biomarker_forest.Rmd
  design/design_cmt01.Rmd
  design/design_cmt02_pt.Rmd
  design/design_combination_forest.Rmd
  design/design_count_subjects_events.Rmd
  design/design_coxt01.Rmd
  design/design_coxt02.Rmd
  design/design_disclosures.Rmd
  design/design_dort01.Rmd
  design/design_dst01.Rmd
  design/design_dth01.Rmd
  design/design_egt01.Rmd
  design/design_egt02.Rmd
  design/design_egt03.Rmd
  design/design_egt04.Rmd
  design/design_egt05_qtcat.Rmd
  design/design_fstg02_table.Rmd
  design/design_h_append_grade_groups.Rmd
  design/design_h_map_for_count_abnormal.Rmd
  design/design_h_map_for_count_abnormal_by_worst_grade.Rmd
  design/design_kmg01.Rmd
  design/design_lbt01.Rmd
  design/design_lbt02.Rmd
  design/design_lbt04.Rmd
  design/design_lbt05.Rmd
  design/design_lbt05_spl_context.Rmd
  design/design_lbt06.Rmd
  design/design_lbt07.Rmd
  design/design_lbt07_spl_context.Rmd
  design/design_lbt08.Rmd
  design/design_lbt09.Rmd
  design/design_lbt10.Rmd
  design/design_lbt10_bl.Rmd
  design/design_lbt12.Rmd
  design/design_lbt12_bl.Rmd
  design/design_lbt13.Rmd
  design/design_lgrt02-interaction.Rmd
  design/design_lgrt02.Rmd
  design/design_mmrm_single_arm.Rmd
  design/design_mmrmt01.Rmd
  design/design_mng01.Rmd
  design/design_onct05.Rmd
  design/design_pruning.Rmd
  design/design_ratet01.Rmd
  design/design_rmpt03_rmpt05.Rmd
  design/design_rspt01.Rmd
  design/design_separate_coxmodels.Rmd
  design/design_step.Rmd
  design/design_summarize_vars_percentiles.Rmd
  design/design_vst01.Rmd
  design/design_vst02.Rmd
Labels: enhancement, sme

#651 Fixed bug in s_ancova, avoid error when the first level of arm factor…
  NEWS.md
  R/summarize_ancova.R
Labels: bug, sme
