Repository insightsengineering/tern, pull requests merged in 2022-12, with the labels that each got.

#758 set count_fraction default format to format_count_fraction
  NAMESPACE
  NEWS.md
  R/count_occurrences.R
  R/count_occurrences_by_grade.R
  R/count_patients_with_event.R
  R/formats.R
  _pkgdown.yml
  man/count_occurrences.Rd
  man/count_occurrences_by_grade.Rd
  man/count_patients_with_event.Rd
  man/extreme_format.Rd
  man/format_count_fraction.Rd
  man/format_count_fraction_fixed_dp.Rd
  man/format_fraction.Rd
  man/format_fraction_fixed_dp.Rd
  man/format_fraction_threshold.Rd
  man/formatting_functions.Rd
  tests/testthat/test-count_occurrences.R
  tests/testthat/test-count_patients_with_event.R
  tests/testthat/test-formats.R
  tests/testthat/test-table_aet01.R
  tests/testthat/test-table_aet02.R
  tests/testthat/test-table_aet03.R
  tests/testthat/test-table_aet06.R
  tests/testthat/test-table_aet06_smq.R
  tests/testthat/test-table_aet09.R
  tests/testthat/test-table_cmt01.R
  tests/testthat/test-table_cmt02_pt.R
  tests/testthat/test-table_lbt14.R
  tests/testthat/test-table_mht01.R
Labels: sme

#760 744 Fix `h_glm_negbin` note
  R/summarize_glm_count.R
Labels: sme

#756 Complete pkct01
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/argument_convention.R
  R/summarize_variables_in_cols.R
  R/summarize_vars_in_cols.R
  man/argument_convention.Rd
  man/compare_variables.Rd
  man/h_map_for_count_abnormal.Rd
  man/h_stack_by_baskets.Rd
  man/summarize_variables.Rd
  man/summarize_variables_in_columns.Rd
  man/summarize_vars_in_cols.Rd
  tests/testthat/setup1-libraries.R
  tests/testthat/setup2-data.R
  tests/testthat/test-summarize_variables_in_cols.R
  tests/testthat/test-table_pkct01.R
  tests/testthat/test-table_pkpc01.R
  tests/testthat/test-table_pkpt03_05_07.R
Labels: enhancement, sme, priority

#768 720 Remove `replace_emptys_with_na`
  R/df_explicit_na.R
  R/logistic_regression.R
  R/utils_factor.R
  man/df_explicit_na.Rd
  man/logistic_regression.Rd
  man/replace_emptys_with_na.Rd
  tests/testthat/test-logistic_regression.R
  tests/testthat/test-table_lgrt02.R
Labels: enhancement, sme

#774 Add ADAT03 test
  NEWS.md
  tests/testthat/setup2-data.R
  tests/testthat/test-table_adat03.R
Labels: documentation, sme

#775 773 export format xx
  NAMESPACE
  NEWS.md
  R/formats.R
  man/format_xx.Rd
Labels: sme

#776 Create `analyze_num_patients` and correct ae* tables
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/argument_convention.R
  R/score_occurrences.R
  R/summarize_num_patients.R
  R/utils_rtables.R
  _pkgdown.yml
  man/argument_convention.Rd
  man/score_occurrences.Rd
  man/summarize_num_patients.Rd
  man/to_string_matrix.Rd
  tests/testthat/test-summarize_num_patients.R
  tests/testthat/test-table_aet02.R
  tests/testthat/test-table_aet02_smq.R
  tests/testthat/test-table_aet03.R
  tests/testthat/test-table_aet06.R
  tests/testthat/test-table_aet06_smq.R
  tests/testthat/test-table_aet07.R
  tests/testthat/test-table_aet09.R
  tests/testthat/test-table_aet09_smq.R
  tests/testthat/test-table_cmt01.R
  tests/testthat/test-table_mht01.R
  tests/testthat/test-utils_rtables.R
Labels: enhancement, sme
