Repository insightsengineering/tern, pull requests merged in 2022-08, with the labels that each got.

#661 Add summary_in_cols.logical
  NAMESPACE
  R/summarize_variables_in_cols.R
  man/summarize_variables_in_columns.Rd
Labels: sme

#669 665: Add `mean_se` to `summarize_variables()` and friends.
  NEWS.md
  R/summarize_change.R
  R/summarize_variables.R
  man/summarize_variables.Rd
  tests/testthat/test-compare_variables.R
  tests/testthat/test-summarize_change.R
  tests/testthat/test-summarize_variables.R
Labels: sme, priority

#670 668 Remove URL
  NEWS.md
  R/prop_diff_test.R
  inst/WORDLIST
  man/prop_diff_test.Rd
Labels: sme

#663 638 Add mean p-value statistics function
  NAMESPACE
  NEWS.md
  R/stat.R
  R/summarize_change.R
  R/summarize_variables.R
  R/utils.R
  _pkgdown.yml
  man/control_summarize_vars.Rd
  man/f_pval.Rd
  man/stat_mean_pval.Rd
  man/summarize_variables.Rd
  tests/testthat/test-compare_variables.R
  tests/testthat/test-stat.R
  tests/testthat/test-summarize_change.R
  tests/testthat/test-summarize_variables.R
  tests/testthat/test-utils.R
Labels: sme

#676 Update cdisc data into rcd_2022_02_28 to fix the test
  tests/testthat/test-count_patients_with_event.R
Labels: sme

#677 673 Fix `h_survival_biomarkers_subgroups` tests
  tests/testthat/test-h_survival_biomarkers_subgroups.R
Labels: sme

#678 672 Fix `h_response_biomarkers_subgroups` tests
  tests/testthat/test-h_response_biomarkers_subgroups.R
Labels: sme

#679 still need to export combine_vectors because needed in tern.mmrm
  NAMESPACE
  NEWS.md
  R/utils.R
  _pkgdown.yml
  man/combine_vectors.Rd
Labels: sme

#680 674 675 cidisc update and fix
  tests/testthat/test-response_biomarkers_subgroups.R
  tests/testthat/test-survival_biomarkers_subgroups.R
Labels: sme

#641 620 wald correction update@main
  DESCRIPTION
  NEWS.md
  R/desctools_binom_diff.R
  R/prop_diff.R
  _pkgdown.yml
  inst/WORDLIST
  man/desctools_binom.Rd
  man/prop_diff.Rd
  tests/testthat/test-prop_diff.R
Labels: sme

#684 683 fix test var labels changes@main
  NEWS.md
  R/h_stack_by_baskets.R
  tests/testthat/test-h_stack_by_baskets.R
Labels: sme

#690 687 fix from formatters na str@main
  NEWS.md
  R/coxph.R
  tests/testthat/test-response_subgroups.R
  tests/testthat/test-summarize_ancova.R
  tests/testthat/test-summarize_variables.R
  tests/testthat/test-survival_duration_subgroups.R
  tests/testthat/test-table_egt01.R
  tests/testthat/test-table_lbt01.R
  tests/testthat/test-table_vst01.R
Labels: bug, sme

#688 add param 'interacton_y' and 'interaction_item' to get the interactio…
  NEWS.md
  R/summarize_ancova.R
  man/compare_variables.Rd
  man/summarize_ancova.Rd
  man/summarize_variables.Rd
  tests/testthat/test-summarize_ancova.R
Labels: sme

#693 692 Fix count_abnormal_by_worst_grade PARAM bug
  NEWS.md
  R/abnormal_by_worst_grade.R
Labels: sme

#695 694 fix stats ancova old versions@main
  NEWS.md
  R/coxph.R
  tests/testthat/test-summarize_ancova.R
Labels: sme
