Repository insightsengineering/tern, pull requests merged in 2022-10, with the labels that each got.

#721 Clean `NEWS.md`
  NEWS.md
Labels: documentation, sme

#726 725 Fix `h_ancova` bug
  NEWS.md
  R/summarize_ancova.R
Labels: bug, sme

#729 713 `summarize_occurrences_by_grade` missing numeric grades bug
  NEWS.md
  R/count_occurrences_by_grade.R
Labels: bug, sme

#731 adding tern.gee to staged.deps
  staged_dependencies.yaml
Labels: sme
