Repository insightsengineering/tern, pull requests merged in 2022-09, with the labels that each got.

#701 698 Remove deprecated `tern` functions
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/argument_convention.R
  R/coxph.R
  R/deprec-nest_colors.R
  R/g_forest.R
  R/individual_patient_plot.R
  _pkgdown.yml
  man/add_footnotes-set.Rd
  man/argument_convention.Rd
  man/color_palette.Rd
  man/footnotes-set.Rd
  man/footnotes.Rd
  man/individual_patient_plot.Rd
  man/s_cox_univariate.Rd
  tests/testthat/test-coxreg.R
Labels: sme

#696 588 adding stratified newcombe@main
  NAMESPACE
  R/estimate_multinomial_rsp.R
  R/estimate_proportion.R
  R/h_response_subgroups.R
  R/prop_diff.R
  R/utils_checkmate.R
  inst/WORDLIST
  man/check_diff_prop_ci.Rd
  man/d_proportion.Rd
  man/estimate_proportions.Rd
  man/prop_diff.Rd
  man/strata_normal_quantile.Rd
  man/update_weights_strat_wilson.Rd
  tests/testthat/test-estimate_multinom_rsp.R
  tests/testthat/test-estimate_proportion.R
  tests/testthat/test-prop_diff.R
  tests/testthat/test-table_pkpt02_04_06.R
Labels: sme, priority

#706 705 Fix `nestcolor` CRAN check note
  DESCRIPTION
Labels: sme

#710 Add tests for `prop_strat_wilson` and `prop_diff_strat_nc`
  NEWS.md
  tests/testthat/test-estimate_proportion.R
  tests/testthat/test-prop_diff.R
Labels: sme

#714 711 Add footnotes parameter to `g_km`
  NEWS.md
  R/kaplan_meier_plot.R
  man/g_km.Rd
  man/h_decompose_gg.Rd
  man/h_ggkm.Rd
  man/h_grob_tbl_at_risk.Rd
  man/h_grob_y_annot.Rd
  man/h_km_layout.Rd
  man/kaplan_meier.Rd
Labels: sme, priority

#715 reintroducing Rdpack
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/estimate_proportion.R
  R/prop_diff.R
  R/wrap_text.R
  inst/REFERENCES.bib
  man/estimate_proportions.Rd
  man/prop_diff.Rd
  man/strata_normal_quantile.Rd
Labels: enhancement, sme, automation

#718 586 Fill empty weights for `prop_diff_strat_nc`
  R/prop_diff.R
Labels: sme
