Repository insightsengineering/tern, pull requests merged in 2022-06, with the labels that each got.

#596 pkgdown desc full sentence
  _pkgdown.yml
Labels: documentation, sme

#600 597 only checkmate@main
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/abnormal.R
  R/abnormal_by_baseline.R
  R/abnormal_by_marked.R
  R/abnormal_by_worst_grade.R
  R/abnormal_by_worst_grade_worsen.R
  R/compare_variables.R
  R/control_step.R
  R/count_occurrences.R
  R/count_occurrences_by_grade.R
  R/cox_regression.R
  R/df_explicit_na.R
  R/estimate_multinomial_rsp.R
  R/fit_rsp_step.R
  R/fit_survival_step.R
  R/formats.R
  R/h_map_for_count_abnormal.R
  R/h_pkparam_sort.R
  R/h_response_biomarkers_subgroups.R
  R/h_response_subgroups.R
  R/h_stack_by_baskets.R
  R/h_step.R
  R/h_survival_biomarkers_subgroups.R
  R/h_survival_duration_subgroups.R
  R/incidence_rate.R
  R/kaplan_meier_plot.R
  R/logistic_regression.R
  R/odds_ratio.R
  R/prop_diff.R
  R/prop_diff_test.R
  R/split_cols_by_groups.R
  R/summarize_ancova.R
  R/summarize_change.R
  R/summarize_num_patients.R
  R/summarize_patients_exposure_in_cols.R
  R/summarize_variables.R
  R/survival_coxph_pairwise.R
  R/survival_time.R
  R/survival_timepoint.R
  R/utils_checkmate.R
  R/utils_rtables.R
  _pkgdown.yml
  man/assertions.Rd
  man/count_occurrences_by_grade.Rd
  man/h_tbl_median_surv.Rd
  tests/testthat/test-summarize_variables.R
  tests/testthat/test-utils_checkmate.R
Labels: enhancement, sme, core

#601 289 Deprecate `tern::color_palette`
  DESCRIPTION
  NEWS.md
  R/deprec-nest_colors.R
  R/zzz.R
  _pkgdown.yml
  man/color_palette.Rd
  staged_dependencies.yaml
Labels: sme

#615 613 Remove `tern:::` prefix from tern tests
  NEWS.md
  tests/testthat/test-abnormal.R
  tests/testthat/test-abnormal_by_baseline.R
  tests/testthat/test-abnormal_by_marked.R
  tests/testthat/test-abnormal_by_worst_grade.R
  tests/testthat/test-abnormal_by_worst_grade_worsen.R
  tests/testthat/test-estimate_incidence_rate.R
  tests/testthat/test-formats.R
  tests/testthat/test-h_format_row.R
  tests/testthat/test-h_response_biomarkers_subgroups.R
  tests/testthat/test-h_survival_biomarkers_subgroups.R
  tests/testthat/test-h_survival_duration_subgroups.R
  tests/testthat/test-logistic_regression.R
  tests/testthat/test-prune_occurrences.R
  tests/testthat/test-response_subgroups.R
  tests/testthat/test-rtables_access.R
  tests/testthat/test-split_cols_by_groups.R
  tests/testthat/test-summarize_ancova.R
  tests/testthat/test-summarize_change.R
  tests/testthat/test-summarize_patients_exposure_in_cols.R
  tests/testthat/test-survival_coxph_pairwise.R
  tests/testthat/test-survival_duration_subgroups.R
  tests/testthat/test-survival_time.R
  tests/testthat/test-survival_timepoint.R
  tests/testthat/test-table_lgrt02.R
  tests/testthat/test-test_proportion_diff.R
  tests/testthat/test-utils.R
  tests/testthat/test-utils_factor.R
Labels: sme

#616 export functions for biomarkers
  NAMESPACE
  NEWS.md
  R/utils.R
  R/utils_factor.R
  _pkgdown.yml
  man/fct_collapse_only.Rd
  man/fct_explicit_na_if.Rd
  man/month2day.Rd
Labels: bug, sme, priority, automation, biomarker

#619 609 Fix warnings in example tests
  NEWS.md
  R/compare_variables.R
  R/g_lineplot.R
  R/prop_diff.R
  R/summarize_variables.R
  R/utils_grid.R
  man/compare_variables.Rd
  man/prop_diff.Rd
  man/stack_grobs.Rd
  man/summarize_variables.Rd
Labels: sme
