Repository insightsengineering/tern, pull requests merged in 2022-11, with the labels that each got.

#734 733 Add more tests to `tern`
  NEWS.md
  tests/testthat/test-abnormal_by_baseline.R
  tests/testthat/test-count_patients_with_event.R
  tests/testthat/test-coxph.R
  tests/testthat/test-decorate_grob.R
  tests/testthat/test-desctools_binom_diff.R
  tests/testthat/test-estimate_proportion.R
  tests/testthat/test-fit_rsp_step.R
  tests/testthat/test-fit_survival_step.R
  tests/testthat/test-footnotes.R
  tests/testthat/test-formats.R
  tests/testthat/test-g_lineplot.R
  tests/testthat/test-g_step.R
  tests/testthat/test-g_waterfall.R
  tests/testthat/test-h_response_biomarkers_subgroups.R
  tests/testthat/test-h_survival_biomarkers_subgroups.R
  tests/testthat/test-h_survival_duration_subgroups.R
  tests/testthat/test-individual_patient_plot.R
  tests/testthat/test-kaplan_meier_plot.R
  tests/testthat/test-odds_ratio.R
  tests/testthat/test-prop_diff.R
  tests/testthat/test-response_biomarkers_subgroups.R
  tests/testthat/test-stat.R
  tests/testthat/test-summarize_ancova.R
  tests/testthat/test-summarize_variables_in_cols.R
  tests/testthat/test-survival_biomarkers_subgroups.R
  tests/testthat/test-survival_duration_subgroups.R
  tests/testthat/test-table_aet01.R
  tests/testthat/test-table_aet04.R
  tests/testthat/test-table_dmt01.R
  tests/testthat/test-table_dth01.R
  tests/testthat/test-table_egt02.R
  tests/testthat/test-table_ent.R
  tests/testthat/test-table_fstg02.R
  tests/testthat/test-table_lbt05.R
  tests/testthat/test-table_mht01.R
  tests/testthat/test-table_onct05.R
  tests/testthat/test-table_pkpt03_05_07.R
  tests/testthat/test-table_rspt01.R
  tests/testthat/test-table_vst02.R
  tests/testthat/test-utils_grid.R
  tests/testthat/test-wrap_text.R
Labels: documentation, sme

#735 added deprecated badge
  NEWS.md
  R/wrap_text.R
Labels: sme

#739 401 add rate01 tlg@main
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/summarize_glm_count.R
  inst/WORDLIST
  man/summarize_glm_count.Rd
  tests/testthat/test-summarize_glm_count.R
Labels: sme

#741 740 qplot warning failure@main
  R/decorate_grob.R
  R/wrap_text.R
  man/decorate_grob.Rd
  man/decorate_grob_set.Rd
  tests/testthat/test-decorate_grob.R
  tests/testthat/test-g_km.R
  tests/testthat/test-wrap_text.R
Labels: bug, sme, priority

#745 citril dep
  staged_dependencies.yaml
Labels: sme

#750 Fix tests
  tests/testthat/test-coxph.R
  tests/testthat/test-summarize_glm_count.R
Labels: bug, sme

#746 add warning for negative binomial. Increase test coverage.
  R/summarize_glm_count.R
  tests/testthat/test-summarize_glm_count.R
Labels: sme

#753 Adding test to improve code coverage.
  tests/testthat/test-summarize_glm_count.R
Labels: sme

#755 754 Add formatting function with fixed single decimal place
  NAMESPACE
  NEWS.md
  R/formats.R
  _pkgdown.yml
  man/extreme_format.Rd
  man/format_count_fraction.Rd
  man/format_fraction.Rd
  man/format_fraction_fixed_dp.Rd
  man/format_fraction_threshold.Rd
  man/formatting_functions.Rd
  tests/testthat/test-formats.R
Labels: enhancement, sme
