Repository insightsengineering/tern, pull requests merged in 2023-10, with the labels that each got.

#1072 Fix snapshot differences (it may need muting `h_ppmeans()`)
  tests/testthat/_snaps/utils_default_stats_formats_labels.md
  tests/testthat/test-summarize_glm_count.R
  tests/testthat/test-utils_default_stats_formats_labels.R
Labels: bug, sme, automation

#1074 [skip vbump] release v0.9.1
  DESCRIPTION
  NEWS.md
  tests/testthat/_snaps/summarize_glm_count.md
  tests/testthat/test-summarize_glm_count.R
  tests/testthat/test-utils_default_stats_formats_labels.R
Labels: sme, release

#1079 Fix `s_summary` return for empty logical vectors
  NEWS.md
  R/analyze_variables.R
  man/analyze_variables.Rd
  tests/testthat/_snaps/analyze_variables.md
  tests/testthat/test-analyze_variables.R
Labels: sme

#1082 Fix `g_km` unit conversion bug
  NEWS.md
  R/kaplan_meier_plot.R
Labels: sme

#1089 1086 update plot snaps@main
  tests/testthat/_snaps/g_forest/g-forest-custom.svg
  tests/testthat/_snaps/g_forest/g-forest.svg
  tests/testthat/_snaps/g_km/grob-tmp-char.svg
  tests/testthat/_snaps/g_km/grob-tmp-ci.svg
  tests/testthat/_snaps/g_km/grob-tmp.svg
  tests/testthat/_snaps/g_lineplot/g-lineplot-w-stats.svg
  tests/testthat/_snaps/g_lineplot/g-lineplot.svg
  tests/testthat/_snaps/g_step/g-step-custom.svg
  tests/testthat/_snaps/g_step/g-step.svg
  tests/testthat/_snaps/g_waterfall/g-waterfall-decorated.svg
  tests/testthat/_snaps/g_waterfall/g-waterfall.svg
  tests/testthat/test-g_forest.R
  tests/testthat/test-g_km.R
  tests/testthat/test-g_lineplot.R
  tests/testthat/test-g_step.R
  tests/testthat/test-g_waterfall.R
Labels: sme

#1091 Update logo
  man/figures/tern.png
Labels: sme

#1093 Fix logo sizing on pkgdown site
  README.md
Labels: sme

#1095 Update `analyze_vars _in_cols` to allow non-numeric nominal timepoint variable
  NEWS.md
  R/analyze_vars_in_cols.R
  tests/testthat/test-analyze_vars_in_cols.R
Labels: sme, priority

#1078 update g_lineplot with cohort param.
  R/g_lineplot.R
  man/control_lineplot_vars.Rd
  man/g_lineplot.Rd
  tests/testthat/_snaps/g_lineplot/g-lineplot-cohorts.svg
  tests/testthat/test-g_lineplot.R
Labels: sme

#1097 Fix integration for version 9.1
  tests/testthat/_snaps/g_forest/g-forest.svg
  tests/testthat/_snaps/response_subgroups.md
  tests/testthat/_snaps/survival_duration_subgroups.md
Labels: sme

#1099 remove `USUBJID` hard coding
  R/abnormal_by_worst_grade.R
  R/g_lineplot.R
Labels: sme

#1104 Fix all lint
  R/decorate_grob.R
  R/desctools_binom_diff.R
  R/response_subgroups.R
  R/utils_default_stats_formats_labels.R
  data-raw/generate_tern_data.Rmd
  tests/testthat/test-abnormal_by_marked.R
Labels: sme

#1107 [skip vbump] Release Candidate 0.9.2
  DESCRIPTION
  NEWS.md
Labels: sme, release

#1012 Adds min package version
  .github/workflows/scheduled.yaml
  DESCRIPTION
  NEWS.md
Labels: blocked, core

#1110 Improve documentation of `whiskers` param in `g_lineplot`
  R/g_lineplot.R
  man/g_lineplot.Rd
Labels: sme

#1076 Refactor `count_occurrences`
  NAMESPACE
  NEWS.md
  R/count_occurrences.R
  R/riskdiff.R
  R/summarize_functions.R
  R/utils_default_stats_formats_labels.R
  man/afun_riskdiff.Rd
  man/count_occurrences.Rd
  man/default_stats_formats_labels.Rd
  man/summarize_functions.Rd
  tests/testthat/_snaps/count_occurrences.md
  tests/testthat/_snaps/utils_default_stats_formats_labels.md
  tests/testthat/test-count_occurrences.R
  tests/testthat/test-utils_default_stats_formats_labels.R
Labels: sme

#1111 Add split functions for `ref_group` position
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/utils_split_funs.R
  _pkgdown.yml
  man/utils_split_funs.Rd
  tests/testthat/_snaps/utils_split_fun.md
  tests/testthat/test-utils_split_fun.R
Labels: enhancement, sme
