Repository insightsengineering/tern, pull requests merged in 2023-03, with the labels that each got.

#843 Fix bug in `add_rowcounts`
  NEWS.md
  R/utils_rtables.R
  man/add_rowcounts.Rd
  man/c_label_n.Rd
  tests/testthat/_snaps/utils_rtables.md
  tests/testthat/test-utils_rtables.R
Labels: sme

#848 Update README.md
  README.md
Labels: sme

#853 Added var_labels argument
  R/prop_diff_test.R
  man/prop_diff_test.Rd
  tests/testthat/test-test_proportion_diff.R
Labels: sme

#855 Prepare for v0.8.0 release [skip vbump]
  DESCRIPTION
  NEWS.md
  README.md
Labels: sme, priority

#861 Fix dates in `tern` data [skip vbump]
  DESCRIPTION
  NEWS.md
  data/tern_ex_adae.rda
  data/tern_ex_adlb.rda
  data/tern_ex_adpp.rda
  data/tern_ex_adrs.rda
  data/tern_ex_adsl.rda
  data/tern_ex_adtte.rda
  tests/testthat/_snaps/abnormal_by_marked.md
  tests/testthat/_snaps/abnormal_by_worst_grade_worsen.md
  tests/testthat/_snaps/h_adsl_adlb_merge_using_worst_flag.md
  tests/testthat/_snaps/h_stack_by_baskets.md
  tests/testthat/_snaps/rtables_access.md
  tests/testthat/_snaps/test_proportion_diff.md
  tests/testthat/test-rtables_access.R
  vignettes/generate_tern_data.Rmd
Labels: sme

#863 Fix missing label for `TRTEDTM` in `tern` data [skip vbump]
  data/tern_ex_adae.rda
  data/tern_ex_adlb.rda
  data/tern_ex_adpp.rda
  data/tern_ex_adrs.rda
  data/tern_ex_adsl.rda
  data/tern_ex_adtte.rda
  vignettes/generate_tern_data.Rmd
Labels: bug, sme

#864 [skip vbump] replacing version from 0.8.0 to 0.8.1
  DESCRIPTION
  NEWS.md
Labels: sme

#870 Use `argument_convention` instead of templates
  .Rbuildignore
  R/argument_convention.R
  R/compare_variables.R
  R/decorate_grob.R
  R/estimate_proportion.R
  R/g_waterfall.R
  R/prop_diff.R
  R/summarize_colvars.R
  R/summarize_variables.R
  man-roxygen/author_liaoc10.R
  man-roxygen/author_manukyae.R
  man-roxygen/author_qit3.R
  man-roxygen/author_song24.R
  man-roxygen/author_stoilovs.R
  man-roxygen/author_waddella.R
  man-roxygen/author_wangh107.R
  man-roxygen/author_zhanc107.R
  man-roxygen/formatting_arguments.R
  man-roxygen/param_is_event.R
  man-roxygen/return_rtable.R
  man/analyze_vars_in_cols.Rd
  man/argument_convention.Rd
  man/compare_variables.Rd
  man/summarize_colvars.Rd
  man/summarize_variables.Rd
Labels: sme

#868 moving out data generator script from user-facing doc
  .Rbuildignore
  data-raw/generate_tern_data.Rmd
Labels: enhancement, sme

#872 Organization of ignores
  .Rbuildignore
  .gitignore
  NEWS.md
Labels: enhancement, sme, automation
