Repository insightsengineering/tern, pull requests merged in 2023-05, with the labels that each got.

#894 Fix GRAN build errors
  DESCRIPTION
Labels: sme

#895 alphabetical order of staged.deps + biomarker-catalog
  DESCRIPTION
  staged_dependencies.yaml
Labels: sme, automation

#902 deprecating `pairwise`
  NEWS.md
  R/coxph.R
  _pkgdown.yml
  man/pairwise.Rd
  tests/testthat/_snaps/coxph.md
  tests/testthat/test-coxph.R
Labels: sme

#904 Update level order in `d_onco_rsp_label`
  NEWS.md
  R/estimate_multinomial_rsp.R
  tests/testthat/_snaps/estimate_multinom_rsp.md
Labels: sme

#907 Move `count_patients_with_flags` functions into a separate file
  DESCRIPTION
  NEWS.md
  R/count_patients_with_event.R
  R/count_patients_with_flags.R
  man/count_patients_with_event.Rd
  man/count_patients_with_flags.Rd
  tests/testthat/_snaps/count_patients_with_event.md
  tests/testthat/_snaps/count_patients_with_flags.md
  tests/testthat/test-count_patients_with_event.R
  tests/testthat/test-count_patients_with_flags.R
Labels: sme

#909 Check all URLs
  LICENSE
  README.md
  vignettes/tables.Rmd
  vignettes/tern.Rmd
Labels: sme

#908 Update overview pages
  DESCRIPTION
  NEWS.md
  R/abnormal.R
  R/analyze_colvars_functions.R
  R/analyze_functions.R
  R/compare_variables.R
  R/count_occurrences_by_grade.R
  R/count_patients_events_in_cols.R
  R/estimate_multinomial_rsp.R
  R/formatting_functions.R
  R/h_biomarkers_subgroups.R
  R/kaplan_meier_plot.R
  R/logistic_regression.R
  R/response_subgroups.R
  R/summarize_colvars.R
  R/summarize_coxreg.R
  R/summarize_functions.R
  R/summarize_patients_exposure_in_cols.R
  R/survival_duration_subgroups.R
  R/utils_rtables.R
  _pkgdown.yml
  inst/WORDLIST
  man/add_rowcounts.Rd
  man/analyze_colvars_functions.Rd
  man/analyze_functions.Rd
  man/compare_variables.Rd
  man/count_occurrences_by_grade.Rd
  man/count_patients_events_in_cols.Rd
  man/cox_regression.Rd
  man/estimate_multinomial_rsp.Rd
  man/extreme_format.Rd
  man/format_count_fraction.Rd
  man/format_count_fraction_fixed_dp.Rd
  man/format_extreme_values.Rd
  man/format_extreme_values_ci.Rd
  man/format_fraction.Rd
  man/format_fraction_fixed_dp.Rd
  man/format_fraction_threshold.Rd
  man/format_xx.Rd
  man/formatting_functions.Rd
  man/g_km.Rd
  man/h_tab_one_biomarker.Rd
  man/kaplan_meier.Rd
  man/logistic_summary_by_flag.Rd
  man/response_subgroups.Rd
  man/summarize_colvars.Rd
  man/summarize_functions.Rd
  man/summarize_patients_exposure_in_cols.Rd
  man/survival_duration_subgroups.Rd
Labels: sme

#916 Add `analyze_patients_exposure_in_cols`
  NAMESPACE
  NEWS.md
  R/analyze_colvars_functions.R
  R/summarize_patients_exposure_in_cols.R
  man/analyze_colvars_functions.Rd
  man/summarize_patients_exposure_in_cols.Rd
  tests/testthat/_snaps/summarize_patients_exposure_in_cols.md
  tests/testthat/test-summarize_patients_exposure_in_cols.R
Labels: sme

#922 Add more informative error to `s_proportion_diff`
  NEWS.md
  R/prop_diff.R
  man/prop_diff.Rd
  tests/testthat/_snaps/summarize_coxreg.md
Labels: sme

#912 Check tests after formatters' changes
  DESCRIPTION
  tests/testthat/test-summarize_num_patients.R
Labels: sme, automation

#927 fixing both validation errors
  tests/testthat/_snaps/summarize_ancova.md
  tests/testthat/test-summarize_ancova.R
  tests/testthat/test-summarize_num_patients.R
Labels: bug, sme

#921 Release v0.8.2 [skip vbump]
  DESCRIPTION
  NEWS.md
  README.md
Labels: blocked, sme

#933 Clean up `.Rbuildignore`
  .Rbuildignore
Labels: sme

#937 Add CRAN installation instructions to README
  NEWS.md
  README.md
  inst/WORDLIST
Labels: sme

#944 Add zero counts to `g_km` annotation table
  NEWS.md
  R/kaplan_meier_plot.R
Labels: sme
