Repository insightsengineering/tern, pull requests merged in 2023-08, with the labels that each got.

#1015 Correct swapped descriptions of `.N_col` and `.N_row` parameters
  NEWS.md
  R/argument_convention.R
  man/analyze_variables.Rd
  man/argument_convention.Rd
  man/c_label_n.Rd
  man/count_missed_doses.Rd
  man/count_occurrences.Rd
  man/count_occurrences_by_grade.Rd
  man/count_patients_with_event.Rd
  man/count_patients_with_flags.Rd
  man/count_values_funs.Rd
  man/estimate_multinomial_rsp.Rd
  man/summarize_num_patients.Rd
  man/summarize_patients_exposure_in_cols.Rd
Labels: sme

#1017 Fix degenerate table warning in `summarize_coxreg`
  R/summarize_coxreg.R
  tests/testthat/test-summarize_coxreg.R
Labels: sme

#1021 Update default `g_km` y limits
  DESCRIPTION
  R/kaplan_meier_plot.R
  man/g_km.Rd
  man/h_ggkm.Rd
  tests/testthat/_snaps/g_km/g-km-crop-ylim.svg
  tests/testthat/_snaps/g_km/g-km-custom-ylim.svg
  tests/testthat/test-g_km.R
Labels: sme

#1014 Ugly fix for categorical data
  NEWS.md
  R/analyze_vars_in_cols.R
  tests/testthat/_snaps/analyze_vars_in_cols.md
  tests/testthat/test-analyze_vars_in_cols.R
Labels: bug, sme

#1028 Adjust `ylim` defaults in `g_km` when `yval = "Failure"`
  R/kaplan_meier_plot.R
  man/formatting_functions.Rd
  tests/testthat/_snaps/g_km/g-km-crop-ylim-failure.svg
  tests/testthat/_snaps/g_km/g-km-crop-ylim.svg
  tests/testthat/_snaps/g_km/g-km-custom-ylim.svg
  tests/testthat/test-g_km.R
Labels: sme, core

#983 Refactor `a_summary`
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/analyze_functions.R
  R/analyze_variables.R
  R/compare_variables.R
  R/summarize_colvars.R
  R/summary_stats.R
  R/utils_factor.R
  _pkgdown.yml
  inst/WORDLIST
  man/a_summary_internal.Rd
  man/analyze_functions.Rd
  man/analyze_variables.Rd
  man/compare_variables.Rd
  man/control_analyze_vars.Rd
  man/create_afun_compare.Rd
  man/create_afun_summary.Rd
  man/summarize_colvars.Rd
  man/summary_formats.Rd
  man/summary_labels.Rd
  man/summary_stats.Rd
  man/ungroup_stats.Rd
  tests/testthat/_snaps/analyze_variables.md
  tests/testthat/_snaps/summarize_glm_count.md
  tests/testthat/_snaps/summary_stats.md
  tests/testthat/test-analyze_variables.R
  tests/testthat/test-compare_variables.R
  tests/testthat/test-summary_stats.R
Labels: sme

#1032 Fix alias export for summarize_vars
  NAMESPACE
  NEWS.md
  R/analyze_variables.R
  _pkgdown.yml
  man/analyze_variables.Rd
Labels: bug, sme

#1034 deprecate_warn instead of stop for create_afun*
  NEWS.md
  R/analyze_variables.R
  R/compare_variables.R
  tests/testthat/test-analyze_variables.R
  tests/testthat/test-compare_variables.R
Labels: sme, automation

#1040 Correct ordering of grade levels in `s_count_occurences_by_grade`
  NEWS.md
  R/count_occurrences_by_grade.R
  tests/testthat/_snaps/count_occurrences_by_grade.md
  tests/testthat/test-count_occurrences_by_grade.R
Labels: sme

#1046 Update snapshots
  tests/testthat/_snaps/summarize_glm_count.md
  tests/testthat/_snaps/summary_stats.md
  tests/testthat/test-summary_stats.R
Labels: sme

#1050 update rtables and formatters versions
  DESCRIPTION
Labels: sme
