Repository insightsengineering/tern, pull requests merged in 2023-01, with the labels that each got.

#789 788 Fix formats and resolve test warnings
  DESCRIPTION
  NEWS.md
  R/count_occurrences.R
  R/count_occurrences_by_grade.R
  R/count_patients_with_event.R
  R/g_lineplot.R
  R/g_step.R
  R/individual_patient_plot.R
  R/kaplan_meier_plot.R
  man/count_occurrences.Rd
  man/count_occurrences_by_grade.Rd
  man/count_patients_with_event.Rd
  tests/testthat/test-count_occurrences_by_grade.R
  tests/testthat/test-table_aet03.R
  tests/testthat/test-table_aet04.R
Labels: bug, documentation, sme

#787 expand score occurrences
  NAMESPACE
  NEWS.md
  R/formats.R
  R/rtables_access.R
  R/score_occurrences.R
  _pkgdown.yml
  man/rtables_access.Rd
  man/score_occurrences.Rd
  tests/testthat/test-rtables_access.R
  tests/testthat/test-score_occurrences.R
  tests/testthat/test-summarize_num_patients.R
  tests/testthat/test-table_aet06.R
  tests/testthat/test-table_aet06_smq.R
  tests/testthat/test-table_aet07.R
  tests/testthat/test-table_cmt01.R
  tests/testthat/test-table_mht01.R
Labels: bug, enhancement, sme

#790 fix summarize occurrences by grade for pagination
  tests/testthat/test-count_occurrences_by_grade.R
  tests/testthat/test-table_aet03.R
  tests/testthat/test-table_aet04.R
Labels: enhancement, sme

#794 Fixing sorting in `count_occurence_by_grade()` tests
  tests/testthat/test-count_occurrences_by_grade.R
Labels: bug, sme

#795 759 document formats@main
  vignettes/tern_formats.Rmd
Labels: sme

#800 799 Fix `summarize_num_patients` labels
  R/summarize_num_patients.R
  man/summarize_num_patients.Rd
  tests/testthat/test-score_occurrences.R
  tests/testthat/test-summarize_num_patients.R
  tests/testthat/test-table_aet02.R
  tests/testthat/test-table_aet02_smq.R
  tests/testthat/test-table_aet04_pi.R
  tests/testthat/test-table_aet06.R
  tests/testthat/test-table_aet06_smq.R
  tests/testthat/test-table_aet09.R
  tests/testthat/test-table_cmt01.R
  tests/testthat/test-table_cmt02_pt.R
  tests/testthat/test-table_mht01.R
Labels: enhancement, sme

#803 fixing g_forest for older versions of testthat
  R/g_forest.R
  tests/testthat/_snaps/table_aet02.md
  tests/testthat/_snaps/table_aet02_smq.md
  tests/testthat/_snaps/table_aet04_pi.md
  tests/testthat/_snaps/table_aet06.md
  tests/testthat/_snaps/table_aet06_smq.md
  tests/testthat/_snaps/table_aet09.md
  tests/testthat/_snaps/table_cmt01.md
  tests/testthat/_snaps/table_cmt02_pt.md
  tests/testthat/_snaps/table_mht01.md
  tests/testthat/test-g_forest.R
Labels: bug, sme, automation

#806 Add option to remove `(n)` suffix in `s_num_patients`
  NEWS.md
  R/summarize_num_patients.R
  man/summarize_num_patients.Rd
  tests/testthat/test-summarize_num_patients.R
Labels: documentation, sme

#809 Update `summarize_ancova` examples to use `iris` data
  NEWS.md
  R/summarize_ancova.R
  man/summarize_ancova.Rd
Labels: documentation, sme, examples
