Repository insightsengineering/tern, pull requests merged in 2023-06, with the labels that each got.

#938 tentative solution for multiple calls of `analyze_vars_in_cols`
  R/analyze_colvars_functions.R
  R/analyze_functions.R
  R/analyze_vars_in_cols.R
  R/argument_convention.R
  R/summarize_colvars.R
  man/analyze_colvars_functions.Rd
  man/analyze_functions.Rd
  man/analyze_vars_in_cols.Rd
  man/argument_convention.Rd
  man/c_label_n.Rd
  man/count_occurrences_by_grade.Rd
  man/count_patients_events_in_cols.Rd
  man/cox_regression.Rd
  man/summarize_colvars.Rd
  man/summarize_num_patients.Rd
  man/summarize_patients_exposure_in_cols.Rd
  tests/testthat/_snaps/analyze_vars_in_cols.md
  tests/testthat/_snaps/survival_timepoint.md
  tests/testthat/test-analyze_vars_in_cols.R
  tests/testthat/test-survival_timepoint.R
Labels: bug, sme

#945 Enable `.indent_mods` argument in all analysis functions
  NEWS.md
  R/argument_convention.R
  R/compare_variables.R
  R/h_biomarkers_subgroups.R
  R/h_response_biomarkers_subgroups.R
  R/h_survival_biomarkers_subgroups.R
  R/logistic_regression.R
  R/response_biomarkers_subgroups.R
  R/summarize_colvars.R
  R/summarize_coxreg.R
  R/summarize_num_patients.R
  R/summarize_variables.R
  R/survival_biomarkers_subgroups.R
  R/survival_time.R
  R/survival_timepoint.R
  R/utils_rtables.R
  inst/WORDLIST
  man/abnormal.Rd
  man/abnormal_by_baseline.Rd
  man/abnormal_by_marked.Rd
  man/abnormal_by_worst_grade.Rd
  man/abnormal_by_worst_grade_worsen.Rd
  man/analyze_vars_in_cols.Rd
  man/argument_convention.Rd
  man/cfun_by_flag.Rd
  man/compare_variables.Rd
  man/count_cumulative.Rd
  man/count_missed_doses.Rd
  man/count_occurrences.Rd
  man/count_occurrences_by_grade.Rd
  man/count_patients_with_event.Rd
  man/count_patients_with_flags.Rd
  man/count_values_funs.Rd
  man/cox_regression.Rd
  man/create_afun_compare.Rd
  man/create_afun_summary.Rd
  man/estimate_multinomial_rsp.Rd
  man/estimate_proportions.Rd
  man/h_response_biomarkers_subgroups.Rd
  man/h_survival_biomarkers_subgroups.Rd
  man/h_tab_one_biomarker.Rd
  man/incidence_rate.Rd
  man/logistic_summary_by_flag.Rd
  man/odds_ratio.Rd
  man/prop_diff.Rd
  man/prop_diff_test.Rd
  man/response_biomarkers_subgroups.Rd
  man/summarize_ancova.Rd
  man/summarize_change.Rd
  man/summarize_colvars.Rd
  man/summarize_glm_count.Rd
  man/summarize_logistic.Rd
  man/summarize_num_patients.Rd
  man/summarize_patients_exposure_in_cols.Rd
  man/summarize_variables.Rd
  man/survival_biomarkers_subgroups.Rd
  man/survival_coxph_pairwise.Rd
  man/survival_time.Rd
  man/survival_timepoint.Rd
Labels: sme

#951 fix rmpt04 total level in `analyze_patients_exposure_in_cols`
  NEWS.md
  R/argument_convention.R
  R/summarize_patients_exposure_in_cols.R
  man/argument_convention.Rd
  man/summarize_patients_exposure_in_cols.Rd
  tests/testthat/_snaps/summarize_patients_exposure_in_cols.md
  tests/testthat/test-summarize_patients_exposure_in_cols.R
Labels: enhancement, sme

#924 Update NA handling by `s_summary`
  NEWS.md
  R/argument_convention.R
  R/compare_variables.R
  R/summarize_variables.R
  man/analyze_vars_in_cols.Rd
  man/argument_convention.Rd
  man/compare_variables.Rd
  man/h_map_for_count_abnormal.Rd
  man/h_stack_by_baskets.Rd
  man/summarize_variables.Rd
  tests/testthat/_snaps/compare_variables.md
  tests/testthat/_snaps/summarize_variables.md
  tests/testthat/_snaps/survival_time.md
  tests/testthat/_snaps/survival_timepoint.md
  tests/testthat/test-compare_variables.R
  tests/testthat/test-summarize_variables.R
Labels: sme

#953 Fix bug in `decorate_grob`
  NEWS.md
  R/decorate_grob.R
  man/decorate_grob.Rd
Labels: sme

#956 Update `summarize_coxreg` to work with pagination in all cases
  NEWS.md
  R/summarize_coxreg.R
  tests/testthat/test-summarize_coxreg.R
Labels: sme

#959 Remove "baseline status" text from abnormal by baseline labels
  NEWS.md
  R/abnormal_by_baseline.R
  tests/testthat/_snaps/abnormal_by_baseline.md
Labels: sme

#963 Fix `NA` value bug in `g_lineplot`
  NEWS.md
  R/g_lineplot.R
Labels: sme

#964 add `--as-cran` to local proj checks
  tern.Rproj
Labels: enhancement, sme, automation

#969 fix formals for `tern:::tidy.glm`
  NEWS.md
  R/logistic_regression.R
  man/tidy.glm.Rd
Labels: bug, sme

#961 Improve annotation scaling in `g_km`
  NEWS.md
  R/kaplan_meier_plot.R
  man/g_km.Rd
  man/h_grob_coxph.Rd
  man/h_grob_median_surv.Rd
Labels: sme

#971 reduce the amount of spelling issues / WORDLIST
  NEWS.md
  R/abnormal_by_worst_grade_worsen.R
  R/control_survival.R
  R/coxph.R
  R/data.R
  R/decorate_grob.R
  R/desctools_binom_diff.R
  R/estimate_proportion.R
  R/g_lineplot.R
  R/h_adsl_adlb_merge_using_worst_flag.R
  R/h_pkparam_sort.R
  R/incidence_rate.R
  R/kaplan_meier_plot.R
  R/prop_diff.R
  R/prop_diff_test.R
  R/prune_occurrences.R
  R/summarize_ancova.R
  R/summarize_colvars.R
  R/summarize_coxreg.R
  R/survival_coxph_pairwise.R
  R/utils.R
  README.md
  inst/WORDLIST
  man/aesi_label.Rd
  man/control_coxph.Rd
  man/control_lineplot_vars.Rd
  man/cox_regression.Rd
  man/desctools_binom.Rd
  man/ex_data.Rd
  man/extract_survival_subgroups.Rd
  man/g_km.Rd
  man/g_lineplot.Rd
  man/h_adlb_worsen.Rd
  man/h_adsl_adlb_merge_using_worst_flag.Rd
  man/h_data_plot.Rd
  man/h_format_row.Rd
  man/h_grob_coxph.Rd
  man/h_grob_median_surv.Rd
  man/h_incidence_rate.Rd
  man/h_pkparam_sort.Rd
  man/h_prop_diff.Rd
  man/h_prop_diff_test.Rd
  man/h_proportions.Rd
  man/h_survival_duration_subgroups.Rd
  man/h_tbl_coxph_pairwise.Rd
  man/h_tbl_median_surv.Rd
  man/prune_occurrences.Rd
  man/s_cox_multivariate.Rd
  man/score_occurrences.Rd
  man/split_text_grob.Rd
  man/summarize_ancova.Rd
  man/summarize_colvars.Rd
  man/survival_coxph_pairwise.Rd
  man/try_car_anova.Rd
  vignettes/tables.Rmd
  vignettes/tern.Rmd
Labels: documentation, core

#975 More intuitive parameter names in `control_incidence_rate`
  NEWS.md
  R/control_incidence_rate.R
  R/incidence_rate.R
  man/control_incidence_rate.Rd
  man/h_incidence_rate.Rd
  man/incidence_rate.Rd
  tests/testthat/test-estimate_incidence_rate.R
Labels: sme

#974 Add `character` method to `h_coxreg_inter_effect`
  NAMESPACE
  NEWS.md
  R/control_incidence_rate.R
  R/cox_regression_inter.R
  man/control_incidence_rate.Rd
  man/cox_regression_inter.Rd
  tests/testthat/test-coxreg.R
  tests/testthat/test-summarize_coxreg.R
Labels: sme

#981 Failure fix for M1mac and noLD - long double problems for `sum(weights)`
  R/estimate_proportion.R
Labels: sme

#987 Fix tests - deprecate `pairwise` and add another test for `format_count_fraction`
  NAMESPACE
  NEWS.md
  R/coxph.R
  _pkgdown.yml
  man/pairwise.Rd
  tests/testthat/test-formats.R
Labels: sme
