Repository insightsengineering/tern, pull requests merged in 2023-04, with the labels that each got.

#875 Remove deprecated footnotes functions
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/footnotes.R
  _pkgdown.yml
  man/add_footnotes-set.Rd
  man/footnotes-set.Rd
  man/footnotes.Rd
  tests/testthat/test-footnotes.R
Labels: sme

#878 Fix tibble snapshots
  tests/testthat/_snaps/abnormal_by_worst_grade_worsen.md
  tests/testthat/_snaps/h_map_for_count_abnormal.md
  tests/testthat/_snaps/h_stack_by_baskets.md
  tests/testthat/_snaps/split_cols_by_groups.md
  tests/testthat/test-abnormal_by_worst_grade_worsen.R
  tests/testthat/test-h_map_for_count_abnormal.R
  tests/testthat/test-h_stack_by_baskets.R
  tests/testthat/test-split_cols_by_groups.R
Labels: sme

#876 858 missing values vignette
  R/df_explicit_na.R
  man/df_explicit_na.Rd
  vignettes/missing_values.Rmd
Labels: sme

#881 fixing argument convention and adding section_div to summarize_vars
  NEWS.md
  R/argument_convention.R
  R/summarize_variables.R
  man/argument_convention.Rd
  man/compare_variables.Rd
  man/count_cumulative.Rd
  man/count_missed_doses.Rd
  man/count_occurrences.Rd
  man/count_occurrences_by_grade.Rd
  man/count_patients_with_event.Rd
  man/estimate_multinomial_rsp.Rd
  man/estimate_proportions.Rd
  man/incidence_rate.Rd
  man/odds_ratio.Rd
  man/prop_diff.Rd
  man/prop_diff_test.Rd
  man/summarize_ancova.Rd
  man/summarize_glm_count.Rd
  man/summarize_num_patients.Rd
  man/summarize_variables.Rd
  man/survival_coxph_pairwise.Rd
  man/survival_time.Rd
  man/survival_timepoint.Rd
Labels: documentation, enhancement, sme

#884 Add `median_range` as a statistic option for `summarize_vars`
  NEWS.md
  R/summarize_variables.R
  man/summarize_variables.Rd
  tests/testthat/_snaps/compare_variables.md
  tests/testthat/_snaps/footnotes.md
  tests/testthat/_snaps/summarize_change.md
  tests/testthat/_snaps/summarize_variables.md
Labels: sme

#882 Refactor cox regression functions to fix table structure
  DESCRIPTION
  NEWS.md
  R/cox_regression.R
  R/summarize_coxreg.R
  inst/WORDLIST
  man/cox_regression.Rd
  tests/testthat/_snaps/coxreg.md
  tests/testthat/_snaps/summarize_coxreg.md
  tests/testthat/test-coxreg.R
  tests/testthat/test-summarize_coxreg.R
Labels: enhancement, sme
