Repository insightsengineering/tern, pull requests merged in 2023-02, with the labels that each got.

#819 Fix `tern` staged deps
  DESCRIPTION
  NAMESPACE
  R/utils.R
  _pkgdown.yml
  man/reapply_varlabels.Rd
  staged_dependencies.yaml
Labels: sme

#817 Replace deprecated `forcats::fct_explicit_na`
  DESCRIPTION
  NEWS.md
  R/missing_data.R
  R/utils_factor.R
  man/fct_explicit_na_if.Rd
  tests/testthat/_snaps/df_explicit_na.md
  tests/testthat/_snaps/summarize_num_patients.md
  tests/testthat/test-df_explicit_na.R
  tests/testthat/test-g_lineplot.R
Labels: sme

#822 Reintroducing tests for `g_lineplot`
  R/g_lineplot.R
  tests/testthat/test-g_lineplot.R
Labels: bug, sme, automation

#826 Deprecate footnotes and removing wrap_text
  DESCRIPTION
  NEWS.md
  R/footnotes.R
  R/g_forest.R
  R/wrap_text.R
  man/add_footnotes-set.Rd
  man/footnotes-set.Rd
  man/footnotes.Rd
  tests/testthat/_snaps/wrap_text.md
  tests/testthat/test-footnotes.R
  tests/testthat/test-wrap_text.R
Labels: enhancement, sme

#828 Fix bugs in `count_abnormal_by_worst_grade` and `summarize_num_patients`
  NEWS.md
  R/abnormal_by_worst_grade.R
  R/summarize_num_patients.R
  man/abnormal_by_worst_grade.Rd
  man/summarize_num_patients.Rd
Labels: bug, sme

#829 Add options to annotate `g_km` with statistics/vertical lines
  NEWS.md
  R/kaplan_meier_plot.R
  man/g_km.Rd
  man/kaplan_meier.Rd
Labels: sme

#833 Apply styler to all remaining `tern` code
  R/abnormal_by_marked.R
  R/abnormal_by_worst_grade_worsen.R
  R/cox_regression_inter.R
  R/coxph.R
  R/d_pkparam.R
  R/estimate_proportion.R
  R/h_biomarkers_subgroups.R
  R/h_response_subgroups.R
  R/h_stack_by_baskets.R
  R/h_survival_duration_subgroups.R
  R/prop_diff.R
  R/response_subgroups.R
  R/rtables_access.R
  R/summarize_patients_exposure_in_cols.R
  R/survival_duration_subgroups.R
  R/utils_checkmate.R
  man/abnormal_by_marked.Rd
  man/rtables_access.Rd
  tests/testthat/test-coxreg.R
  tests/testthat/test-estimate_proportion.R
  tests/testthat/test-fit_rsp_step.R
  tests/testthat/test-h_stack_by_baskets.R
  tests/testthat/test-kaplan_meier_plot.R
  tests/testthat/test-split_cols_by_groups.R
  tests/testthat/test-stat.R
  tests/testthat/test-summarize_num_patients.R
  tests/testthat/test-utils.R
  vignettes/generate_tern_data.Rmd
  vignettes/tables.Rmd
Labels: sme

#835 Add data labels, fix footnote function warnings
  R/footnotes.R
  _pkgdown.yml
  data/tern_ex_adae.rda
  data/tern_ex_adlb.rda
  data/tern_ex_adpp.rda
  data/tern_ex_adrs.rda
  data/tern_ex_adsl.rda
  data/tern_ex_adtte.rda
  man/add_footnotes-set.Rd
  man/ex_data.Rd
  man/footnotes-set.Rd
  man/footnotes.Rd
  tests/testthat/_snaps/h_logistic_regression.md
  tests/testthat/_snaps/h_response_subgroups.md
  tests/testthat/_snaps/h_stack_by_baskets.md
  tests/testthat/_snaps/h_survival_biomarkers_subgroups.md
  tests/testthat/_snaps/h_survival_duration_subgroups.md
  tests/testthat/_snaps/logistic_regression.md
  tests/testthat/_snaps/response_biomarkers_subgroups.md
  tests/testthat/_snaps/response_subgroups.md
  tests/testthat/_snaps/survival_biomarkers_subgroups.md
  tests/testthat/_snaps/survival_duration_subgroups.md
  tests/testthat/test-footnotes.R
  tests/testthat/test-h_response_biomarkers_subgroups.R
  vignettes/generate_tern_data.Rmd
Labels: sme

#840 update version from rtables and formatters
  DESCRIPTION
Labels: sme
