Repository insightsengineering/tern, pull requests merged in 2024-11, with the labels that each got.

#1335 Add table formatting options to `g_lineplot()` - table relative height & font size
  NEWS.md
  R/g_lineplot.R
  man/g_lineplot.Rd
  tests/testthat/_snaps/g_lineplot/g_lineplot_cohorts.svg
  tests/testthat/_snaps/g_lineplot/g_lineplot_factor_levels.svg
  tests/testthat/_snaps/g_lineplot/g_lineplot_plot_only.svg
  tests/testthat/_snaps/g_lineplot/g_lineplot_table_only.svg
  tests/testthat/_snaps/g_lineplot/g_lineplot_w_stats.svg
  tests/testthat/test-g_lineplot.R
Labels: sme

#1343 Refactor `count_patients_with_event()` and `count_patients_with_flags()`
  NEWS.md
  R/count_patients_with_event.R
  R/count_patients_with_flags.R
  man/count_patients_with_event.Rd
  man/count_patients_with_flags.Rd
  tests/testthat/_snaps/count_patients_with_event.md
  tests/testthat/_snaps/count_patients_with_flags.md
  tests/testthat/test-count_patients_with_event.R
  tests/testthat/test-count_patients_with_flags.R
Labels: sme

#1347 Refactor `summarize_change()`
  NEWS.md
  R/summarize_change.R
  R/utils_default_stats_formats_labels.R
  R/utils_rtables.R
  man/default_stats_formats_labels.Rd
  man/summarize_change.Rd
  man/util_handling_additional_fun_params.Rd
  tests/testthat/_snaps/summarize_change.md
  tests/testthat/test-summarize_change.R
  tests/testthat/test-utils_default_stats_formats_labels.R
  vignettes/tern_functions_guide.Rmd
Labels: bug, enhancement, sme, priority, request changes

#1306 1301 feature request add confidence intervals for quantiles in surv time
  NEWS.md
  R/analyze_variables.R
  R/survival_coxph_pairwise.R
  R/survival_time.R
  R/survival_timepoint.R
  R/utils_default_stats_formats_labels.R
  man/analyze_variables.Rd
  man/compare_variables.Rd
  man/summarize_change.Rd
  man/survival_time.Rd
  man/survival_timepoint.Rd
  tests/testthat/_snaps/analyze_variables.md
  tests/testthat/_snaps/compare_variables.md
  tests/testthat/_snaps/summarize_change.md
  tests/testthat/_snaps/survival_coxph_pairwise.md
  tests/testthat/_snaps/survival_time.md
  tests/testthat/_snaps/survival_timepoint.md
  tests/testthat/_snaps/utils_default_stats_formats_labels.md
  tests/testthat/test-utils_rtables.R
Labels: sme, request changes
