Repository insightsengineering/tern, pull requests merged in 2024-02, with the labels that each got.

#1185 Fix pkgdown redirect
  DESCRIPTION
  man/tern-package.Rd
Labels: bug, core

#1189 #nolintr to # nolint
  R/g_forest.R
Labels: core

#1190 Update DESCRIPTION, update author list
  DESCRIPTION
  inst/WORDLIST
  man/tern-package.Rd
Labels: sme

#1194 Skip plot snapshot testing
  tests/testthat/_snaps/decorate_grob/deco-grob-text-wrap.svg
  tests/testthat/_snaps/decorate_grob/deco_grob_text_wrap.svg
  tests/testthat/_snaps/g_forest/g_forest.svg
  tests/testthat/_snaps/g_forest/g_forest_custom_1.svg
  tests/testthat/_snaps/g_forest/g_forest_custom_2.svg
  tests/testthat/_snaps/g_forest/g_forest_custom_3.svg
  tests/testthat/_snaps/g_forest/g_forest_or.svg
  tests/testthat/_snaps/g_forest/g_forest_plot_only.svg
  tests/testthat/_snaps/g_forest/g_forest_table_only.svg
  tests/testthat/_snaps/g_km/g-km-at-risk-title.svg
  tests/testthat/_snaps/g_km/g-km-crop-ylim-failure.svg
  tests/testthat/_snaps/g_km/g-km-crop-ylim.svg
  tests/testthat/_snaps/g_km/g-km-custom-ylim.svg
  tests/testthat/_snaps/g_km/g-km-ref-group-coxph.svg
  tests/testthat/_snaps/g_km/grob-tmp-ci.svg
  tests/testthat/_snaps/g_km/grob-tmp.svg
  tests/testthat/_snaps/g_lineplot/g-lineplot-cohorts.svg
  tests/testthat/_snaps/g_lineplot/g-lineplot-w-stats.svg
  tests/testthat/_snaps/g_lineplot/g-lineplot.svg
  tests/testthat/_snaps/g_lineplot/g_lineplot.svg
  tests/testthat/_snaps/g_lineplot/g_lineplot_cohorts.svg
  tests/testthat/_snaps/g_lineplot/g_lineplot_w_stats.svg
  tests/testthat/_snaps/g_step/g-step-custom.svg
  tests/testthat/_snaps/g_step/g-step.svg
  tests/testthat/_snaps/g_step/g_step.svg
  tests/testthat/_snaps/g_step/g_step_custom.svg
  tests/testthat/_snaps/g_waterfall/g_waterfall.svg
  tests/testthat/_snaps/g_waterfall/g_waterfall_decorated.svg
  tests/testthat/_snaps/utils_ggplot/rtable2gg_colsplits.svg
  tests/testthat/_snaps/utils_ggplot/rtable2gg_cw.svg
  tests/testthat/_snaps/utils_ggplot/rtable2gg_default.svg
  tests/testthat/_snaps/utils_ggplot/rtable2gg_fs.svg
  tests/testthat/_snaps/utils_ggplot/rtable2gg_lblpad.svg
  tests/testthat/setup.R
  tests/testthat/test-decorate_grob.R
  tests/testthat/test-g_km.R
  tests/testthat/test-g_lineplot.R
  tests/testthat/test-g_step.R
  tests/testthat/test-g_waterfall.R
Labels: sme

#1197 Fix typo, ggplot2 update warnings
  R/g_forest.R
  R/utils_rtables.R
  tests/testthat/_snaps/decorate_grob/deco_grob_text_wrap.svg
  tests/testthat/_snaps/g_forest/g_forest.svg
  tests/testthat/_snaps/g_forest/g_forest_custom_1.svg
  tests/testthat/_snaps/g_forest/g_forest_custom_2.svg
  tests/testthat/_snaps/g_forest/g_forest_custom_3.svg
  tests/testthat/_snaps/g_forest/g_forest_or.svg
  tests/testthat/_snaps/g_forest/g_forest_plot_only.svg
  tests/testthat/_snaps/g_km/g-km-at-risk-title.svg
  tests/testthat/_snaps/g_km/g-km-crop-ylim-failure.svg
  tests/testthat/_snaps/g_km/g-km-crop-ylim.svg
  tests/testthat/_snaps/g_km/g-km-custom-ylim.svg
  tests/testthat/_snaps/g_km/g-km-ref-group-coxph.svg
  tests/testthat/_snaps/g_km/grob-tmp-ci.svg
  tests/testthat/_snaps/g_km/grob-tmp.svg
  tests/testthat/_snaps/g_lineplot/g_lineplot.svg
  tests/testthat/_snaps/g_lineplot/g_lineplot_cohorts.svg
  tests/testthat/_snaps/g_lineplot/g_lineplot_w_stats.svg
  tests/testthat/_snaps/g_step/g_step.svg
  tests/testthat/_snaps/g_step/g_step_custom.svg
  tests/testthat/_snaps/g_waterfall/g-waterfall-decorated.svg
  tests/testthat/_snaps/g_waterfall/g-waterfall.svg
  tests/testthat/_snaps/g_waterfall/g_waterfall_decorated.svg
Labels: sme

#1198 Replace `strat` with `strata`
  NEWS.md
  R/h_response_biomarkers_subgroups.R
  R/h_response_subgroups.R
  R/h_survival_biomarkers_subgroups.R
  R/h_survival_duration_subgroups.R
  R/kaplan_meier_plot.R
  R/prop_diff.R
  R/prop_diff_test.R
  R/response_biomarkers_subgroups.R
  R/response_subgroups.R
  R/survival_biomarkers_subgroups.R
  R/survival_coxph_pairwise.R
  R/survival_duration_subgroups.R
  man/extract_rsp_biomarkers.Rd
  man/extract_rsp_subgroups.Rd
  man/extract_survival_biomarkers.Rd
  man/extract_survival_subgroups.Rd
  man/g_km.Rd
  man/h_response_biomarkers_subgroups.Rd
  man/h_response_subgroups.Rd
  man/h_survival_biomarkers_subgroups.Rd
  man/h_survival_duration_subgroups.Rd
  man/h_tbl_coxph_pairwise.Rd
  man/prop_diff_test.Rd
  man/response_subgroups.Rd
  man/survival_coxph_pairwise.Rd
  tests/testthat/test-h_response_biomarkers_subgroups.R
  tests/testthat/test-h_response_subgroups.R
  tests/testthat/test-h_survival_duration_subgroups.R
  tests/testthat/test-kaplan_meier_plot.R
  tests/testthat/test-response_biomarkers_subgroups.R
  tests/testthat/test-response_subgroups.R
  tests/testthat/test-survival_coxph_pairwise.R
  tests/testthat/test-test_proportion_diff.R
Labels: sme

#1192 fix format precision for `format_count_fraction_fixed_dp`
  NEWS.md
  R/formatting_functions.R
  R/utils.R
  man/dot-is_equal_float.Rd
  tests/testthat/test-formats.R
Labels: sme
