Repository insightsengineering/tern, pull requests merged in 2025-02, with the labels that each got.

#1389 Retire `make_afun()` - Batch 3
  .lintr
  DESCRIPTION
  NEWS.md
  R/abnormal.R
  R/abnormal_by_baseline.R
  R/abnormal_by_marked.R
  R/abnormal_by_worst_grade.R
  R/abnormal_lab_worsen_by_baseline.R
  R/count_patients_events_in_cols.R
  R/g_forest.R
  R/g_lineplot.R
  R/h_adsl_adlb_merge_using_worst_flag.R
  R/utils_default_stats_formats_labels.R
  man/abnormal.Rd
  man/abnormal_by_baseline.Rd
  man/abnormal_by_marked.Rd
  man/abnormal_by_worst_grade.Rd
  man/abnormal_lab_worsen_by_baseline.Rd
  man/h_adlb_worsen.Rd
  man/h_worsen_counter.Rd
  tests/testthat/_snaps/abnormal_lab_worsen_by_baseline.md
  tests/testthat/test-abnormal_lab_worsen_by_baseline.R
Labels: sme

#1395 Remove lookup-refs
  .github/workflows/check.yaml
  .github/workflows/docs.yaml
  .github/workflows/scheduled.yaml
Labels: core

#1393 refactor geom sd and fix custom stat order
  NEWS.md
  R/analyze_variables.R
  R/count_values.R
  R/summarize_change.R
  R/utils_default_stats_formats_labels.R
  man/analyze_variables.Rd
  man/compare_variables.Rd
  man/default_stats_formats_labels.Rd
  man/summarize_change.Rd
  tests/testthat/_snaps/analyze_variables.md
  tests/testthat/_snaps/compare_variables.md
  tests/testthat/_snaps/summarize_change.md
  tests/testthat/_snaps/utils_default_stats_formats_labels.md
  tests/testthat/test-analyze_variables.R
Labels: bug, enhancement, sme

#1400 Add in missing analysis function option for custom statistics
  R/abnormal.R
  R/abnormal_by_baseline.R
  R/abnormal_by_marked.R
  R/abnormal_by_worst_grade.R
  R/abnormal_lab_worsen_by_baseline.R
  R/summarize_ancova.R
  R/summarize_change.R
  R/summarize_glm_count.R
Labels: sme

#1394 Retire `make_afun()` - Batch 4
  NEWS.md
  R/estimate_multinomial_rsp.R
  R/estimate_proportion.R
  R/odds_ratio.R
  R/summarize_ancova.R
  R/summarize_glm_count.R
  R/survival_coxph_pairwise.R
  R/survival_timepoint.R
  R/utils_default_stats_formats_labels.R
  R/utils_rtables.R
  _pkgdown.yml
  man/estimate_multinomial_rsp.Rd
  man/estimate_proportion.Rd
  man/h_split_param.Rd
  man/odds_ratio.Rd
  man/survival_coxph_pairwise.Rd
  man/survival_timepoint.Rd
  tests/testthat/_snaps/estimate_multinomial_rsp.md
  tests/testthat/_snaps/survival_coxph_pairwise.md
  tests/testthat/test-estimate_multinomial_rsp.R
  tests/testthat/test-estimate_proportion.R
  tests/testthat/test-survival_coxph_pairwise.R
  tests/testthat/test-utils_rtables.R
Labels: sme

#1398 Refactor `tabulate_*()` functions and deprecate their helper functions
  NEWS.md
  R/analyze_variables.R
  R/h_biomarkers_subgroups.R
  R/h_response_biomarkers_subgroups.R
  R/h_survival_biomarkers_subgroups.R
  R/odds_ratio.R
  R/response_biomarkers_subgroups.R
  R/response_subgroups.R
  R/summarize_ancova.R
  R/summarize_functions.R
  R/summarize_glm_count.R
  R/survival_biomarkers_subgroups.R
  R/survival_coxph_pairwise.R
  R/survival_duration_subgroups.R
  R/utils_default_stats_formats_labels.R
  _pkgdown.yml
  man/h_biomarkers_subgroups.Rd
  man/h_response_biomarkers_subgroups.Rd
  man/h_survival_biomarkers_subgroups.Rd
  man/h_tab_one_biomarker.Rd
  man/response_biomarkers_subgroups.Rd
  man/response_subgroups.Rd
  man/summarize_functions.Rd
  man/survival_biomarkers_subgroups.Rd
  man/survival_duration_subgroups.Rd
  tests/testthat/_snaps/compare_variables.md
  tests/testthat/_snaps/h_biomarkers_subgroups.md
  tests/testthat/_snaps/h_response_biomarkers_subgroups.md
  tests/testthat/_snaps/h_survival_biomarkers_subgroups.md
  tests/testthat/_snaps/response_subgroups.md
  tests/testthat/_snaps/summarize_ancova.md
  tests/testthat/_snaps/summarize_glm_count.md
  tests/testthat/_snaps/survival_duration_subgroups.md
  tests/testthat/test-h_biomarkers_subgroups.R
  tests/testthat/test-h_response_biomarkers_subgroups.R
  tests/testthat/test-h_survival_biomarkers_subgroups.R
  tests/testthat/test-response_subgroups.R
  tests/testthat/test-survival_duration_subgroups.R
Labels: sme
